name: Maven CI/CD Curso

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        java-version: 14
        distribution: 'temurin'
        cache: 'maven'

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
